# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)
DONE

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch


# Create random tensor
tensor= torch.rand(7,7)
tensor


tensor([[0.9264, 0.6742, 0.9682, 0.7146, 0.7531, 0.2024, 0.9994],
        [0.4009, 0.6588, 0.2826, 0.7975, 0.1033, 0.2463, 0.6820],
        [0.8046, 0.0199, 0.8441, 0.2159, 0.6124, 0.8946, 0.6640],
        [0.6680, 0.9530, 0.9877, 0.7853, 0.3314, 0.5254, 0.1044],
        [0.7335, 0.5308, 0.1128, 0.2221, 0.6046, 0.5331, 0.5479],
        [0.2452, 0.2316, 0.3422, 0.3280, 0.0175, 0.6334, 0.8142],
        [0.1726, 0.8987, 0.9658, 0.5029, 0.7478, 0.0496, 0.2093]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor2= torch.rand(7,3)
# Perform matrix multiplication
matmultensor = tensor@tensor2
matmultensor

tensor([[2.3035, 2.9874, 2.1780],
        [1.3431, 1.5741, 1.8552],
        [2.0045, 2.6964, 1.6277],
        [1.8986, 1.8861, 1.9298],
        [1.7108, 2.2836, 1.4487],
        [1.2428, 1.6161, 1.6086],
        [1.3756, 1.4744, 1.3807]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
SEED=0
torch.manual_seed(SEED)
tensor1=torch.rand(7,7)

# Create two random tensors
torch.manual_seed(SEED)
tensor2=torch.rand(7,1)

# Matrix multiply tensors
matmultensor = tensor1@tensor2
matmultensor ##different outuput coz of different pytorch method

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
