# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)
#DONE

NameError: name 'DONE' is not defined

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch


# Create random tensor
tensor= torch.rand(7,7)
tensor


tensor([[0.5950, 0.4795, 0.5955, 0.4766, 0.1519, 0.9094, 0.4152],
        [0.6841, 0.7551, 0.9011, 0.9270, 0.2597, 0.5600, 0.7618],
        [0.3882, 0.8822, 0.8797, 0.6487, 0.1383, 0.0678, 0.5668],
        [0.2318, 0.9768, 0.3994, 0.4857, 0.3990, 0.3369, 0.2025],
        [0.0929, 0.9815, 0.8434, 0.6821, 0.1005, 0.0247, 0.9077],
        [0.1772, 0.7059, 0.2609, 0.8176, 0.1586, 0.4877, 0.4639],
        [0.0715, 0.6085, 0.4730, 0.6184, 0.9582, 0.3253, 0.0840]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor2= torch.rand(7,3)
# Perform matrix multiplication
matmultensor = tensor@tensor2
matmultensor

tensor([[2.1800, 1.8452, 1.8630],
        [2.7106, 2.2019, 2.4947],
        [2.0871, 1.6801, 1.9864],
        [2.1314, 1.7142, 1.6906],
        [2.0942, 1.5081, 1.9296],
        [1.9392, 1.3491, 1.5080],
        [2.3125, 1.5463, 1.5365]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
SEED=0
torch.manual_seed(SEED)
tensor1=torch.rand(7,7)

# Create two random tensors
torch.manual_seed(SEED)
tensor2=torch.rand(7,1)

# Matrix multiply tensors
matmultensor = tensor1@tensor2
matmultensor ##different outuput coz of different pytorch method

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
RANDOMSEED=1234
torch.cuda.manul_seed(RANDOMSEED)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [20]:
# Set random seed
RANDOMSEED=1234

# Check for access to GPU
device="cuda"  if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
torch.manual_seed(RANDOMSEED)
tensor1=torch.rand(2,3)
tensor1_gpu=tensor1.cuda()
torch.manual_seed(RANDOMSEED)
tensor2=torch.rand(2,3)
tensor2_to_gpu=tensor2.cuda()
tensor1_gpu,tensor2_to_gpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [24]:
# Perform matmul on tensor_A and tensor_B
reshape_tensor2=tensor2.reshape(3,2) #or transpose
matmul=tensor1@reshape_tensor2
matmul, matmul.device, matmul.shape

(tensor([[0.1204, 0.3411],
         [0.0666, 0.6596]]),
 device(type='cpu'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [27]:
# Find max
minval=matmul.min()
maxval=matmul.max()
print("Min value:",minval,"\nMax value:",maxval)




Min value: tensor(0.0666) 
Max value: tensor(0.6596)


### 9. Find the maximum and minimum index values of the output of 7.

In [28]:
# Find arg max
minval=matmul.argmin()

# Find arg min
maxval=matmul.argmax()
minval,maxval


(tensor(2), tensor(3))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [30]:
# Set seed
RANDOMSEED=7
torch.manual_seed(RANDOMSEED)

# Create random tensor
randten = torch.rand(1,1,1,10)

# Remove single dimensions
squezed=randten.squeeze()

# Print out tensors and their shapes
randten , randten.shape,squezed,squezed.shape



(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))